---
# Set line length to 100
MD013:
  line_length: 100
  heading_line_length: 100
  code_block_line_length: 100
  code_blocks: true
  tables: true
  headings: true
  strict: false
  stern: false

# Allow inline html
MD033: false
